### ISSUE TITLE
Hangs in IE8

### ISSUE THREAD

**Issue by ghost** [dcneiner/Downloadify#1]
When I add Downloadify with the following code
    window["Downloadify"]["create"](strId, {
        "filename": "responses.csv",
        "data": fnGetCsvResponses,
        onError: function%28) {
            alert('Error');
        },
        "transparent": false,
        "swf": 'http://obsurvey.com/js/external/downloadify.swf',
        "downloadImage": 'http://obsurvey.com/js/external/download.png',
        "width": 100,
        "height": 30,
        "transparent": false,
        "append": false
    });
It just hangs in IE8. IE8 appears to be loading, but the download image never appears, it's just a white blank space. The same code works fine in Firefox and Chrome... I've tried changing transparent and append, but that changes nothing.
You can see it live here:
http://obsurvey.com/Obsurvey.aspx?uid=d94feb5d-952d-4541-a43c-73371e095d53
When you click "Individual responses"
The save file works in FF & Chrome, but not IE8. (looking at innerHTML IE has no params for the flash object)
I updated swfobject.js to the latest version 2.2, now everything works in IE and Firefox. In Chrome the "Save to disk" graphics comes up, but when you click it nothing happens.

**Comment by ghost** [comment]
Setting transparent to false fixed the problem after updating swfobject to V2.2

**Comment by dcneiner** [comment]
It fixed all the problems, including Chrome? Incidentally, I just pushed a new version of Downloadify to the server and it now ships with 2.2 out of the box. Thanks for pointing that out!

**Comment by ghost** [comment]
Yes downloading csv files with downloadify now works in IE8, Chrome, Firefox and Safari
