### ISSUE TITLE
UTF-8 doesn't supported when export to excel file .xls

### ISSUE THREAD

**Issue by trungwebsite** [dcneiner/Downloadify#10]
I used Downloadify to export content to excel file .xls, but it seems UTF-8 doesn't supported. Maybe it belongs to excel structure. But please help me if you have any ideas about this problem.

TrungWebsite.com
Thanks a lot.

**Comment by styfle** [comment]
How did you create an Excel file (besides just changing the extension)? I am looking into exporting an HTML table to javascript myself.

**Comment by abhinit45** [comment]
While Doing export to excel with the code given working in chrome and forefox perfectly but not working in IE8 because IE8 does not support  dataURI for more than 32 kb ,but my file size is more than 32 kb ,so please can u help me in solving this issue.

**Comment by shuidiansky** [comment]
I saw heavy baidu information is said to local.xls files encoding is ANSI, but most of the js code is utf-8
