### ISSUE TITLE
Regular button or <a> link instead of Flash image?

### ISSUE THREAD

**Issue by vrkuvrku** [dcneiner/Downloadify#11]
Hi folks!

Is it somehow possible not to show Flash image with painted button but invoke Save As dialog by regular clicking on a form button or an "a onclick" link  instead?

Thank you!
Martin

**Comment by JesseAldridge** [comment]
+1 for this.  I want to use downloadify with a jquery ui button.

**Comment by jasonmp85** [comment]
I worked around this by supplying a fully transparent image, setting the transparent flag in downloadify to true, and using positioning to position the object element over my link. Then I set a :hover style on the element enclosing both the link and the object elements so the link would get the correct underlining. The user thinks they're clicking a link, and indeed it looks like any other, but they're really clicking the invisible Flash object. Works pretty good.

**Comment by Zectbumo** [comment]
+1

**Comment by dannyfritz** [comment]
Answered by closed issue: https://github.com/dcneiner/Downloadify/issues/6

**Comment by randyburden** [comment]
@jasonmp85 Thanks for the idea. I did the same thing and used something like this to position my button underneath the Flash object:

```
var exportButton = $( "#ExportButton" );

var exportButtonWidth = exportButton.outerWidth();
var exportButtonHeight = exportButton.outerHeight();

var flashObject = $( '[name^="downloadify"]' );

// Set the Flash object to the same size as my button
flashObject.css( { width: exportButtonWidth, height: exportButtonHeight } );

var exportButtonPosition = flashObject.position();

// Set my button directly underneath the Flash object
exportButton.css( { top: exportButtonPosition.top, left: exportButtonPosition.left, position: 'absolute', 'z-index': -1 } );
```
