### ISSUE TITLE
Offline usage?

### ISSUE THREAD

**Issue by thewilmo** [dcneiner/Downloadify#13]
I can't find a source file for downloadify.swf, is it possible to make one available, or post one compiled for offline use?

I want to compile for offline use, since I'm making a web app that will work online client-side, and also have an identical downloadable version for offline use.

**Comment by zhizhangchen** [comment]
Vote for this

**Comment by powtac** [comment]
You will find the source at http://code.google.com/p/swfobject/source/browse/#svn%2Ftags%2Fswfobject_2_2%2Fsrc Please let me know when you managed to create a "offline" version for local usage.

**Comment by ransomweaver** [comment]
I hav the same need for offline use. Is this correct that downloadify.swf is a modification of expressInstall.as/.fla on the swfobject project?

**Comment by ransomweaver** [comment]
Ah, I see the downloadify.as in the src/com dir. You use the expressinstall.fla with that?
