### ISSUE TITLE
No download button in firefox and safari

### ISSUE THREAD

**Issue by slgallagher** [dcneiner/Downloadify#18]
trying the very simple demo example page but the save/download button doesn;t show up in firefox or safari? It does show up in IE and Chrome.

**Comment by aranair** [comment]
edit: its working

**Comment by revolunet** [comment]
works here on firefox 10.0.2 or Safari 5.1.4

**Comment by aranair** [comment]
edited- working

**Comment by revolunet** [comment]
this is the page where i test : http://pixelgraphics.us/downloadify/test.html

any adblock/flashblock ?

**Comment by aranair** [comment]
oh god, this is embarrassing. I didn't have the plugin in Firefox. /dies sorry guys ;P
