### ISSUE TITLE
Add onClick event

### ISSUE THREAD

**Issue by dugokontov** [dcneiner/Downloadify#19]
When a large file is to be generated it takes some 4-5 seconds to do so. Since no change on web UI is made, user may think that he didn't click the icon, and try to click it again. To prevent this, I would like to suggest you to add one more event, _onClick_ that will be fired before _getTextForSave_.

I think changes should be done in those two files:
**Downloadify.as**
add on line 144:

```
ExternalInterface.call('Downloadify.callOnClick',queue_name),
```

**downloadify.js**
add on line 32
```
callOnClick: function(queue){
  var obj = Downloadify.queue[queue];
  if(obj) obj.click();
},
```

add on line 176

```
base.click = function() {
  if(typeof(base.options.onClick) === "function") base.options.onClick();
};
```

Also, note that I have tried to make UI changes in *data* event, but for some reason they are not shown until data generation has been done.

**Comment by damuzu** [comment]
+1
but I need this for converting the image after I click the downloadify button.. and after the converting is done the save dialog is open..
