### ISSUE TITLE
style.display = "none"

### ISSUE THREAD

**Issue by ghost** [dcneiner/Downloadify#2]
When I set style.display = "none" in a div containing a downloadify element, the downloadify element is not hidden.

**Comment by dcneiner** [comment]
I believe that might have to do with Flash. You have `transparent:true` in your code. Try changing that to `false` (Its actually there twice. Remove one of the declarations, and set the remaining on to `false`).

**Comment by dcneiner** [comment]
Glad it is working now, I updated my answer to correctly read `false` in both locations, and am marking this case solved.

**Comment by ghost** [comment]
Actually I commented on the wrong issue, I haven't tested this.

**Comment by dcneiner** [comment]
OK, let me know. I closed the other ticket and reopened this one.
