### ISSUE TITLE
Allow trigger from javascript

### ISSUE THREAD

**Issue by mattinsler** [dcneiner/Downloadify#20]
Support something like Downloadify.download(options).

Or, maybe something like $('#downloader').downloadify('trigger'); to trigger the download to happen.  Just need some way to trigger the download without using the SWF click event.

**Comment by jhpoosthoek** [comment]
That would be very nice!

**Comment by dannyfritz** [comment]
Answered by closed issue: https://github.com/dcneiner/Downloadify/issues/6
