### ISSUE TITLE
Allow resize of Flash shim when browser zoom level is changed

### ISSUE THREAD

**Issue by alexpreynolds** [dcneiner/Downloadify#22]
The AS line:

`stage.scaleMode = StageScaleMode.NO_SCALE`

appears to keep the Flash shim from rescaling the button image when the browser's zoom level is changed. At the moment, when the zoom level is changed, the button does not resize, leading to rendering issues.

Would it be possible to add a small event handler that resizes the button image along with the parent div, when the zoom level is changed?

**Comment by eljeffeg** [comment]
+1
