### ISSUE TITLE
Downloadify won't work when openning local file directly on your browser.

### ISSUE THREAD

**Issue by viclib** [dcneiner/Downloadify#24]
I've tested this on two environments. Downloaditify won't work if you open your site locally. No error. Nothing happens.

**Comment by pedrosino** [comment]
Same here.

**Comment by helder-robalo** [comment]
If you read the README.textile will notice that its build is just to work on 'http' protocol.

Downloadify: Client Side File Creation
Important! The swf has been compiled for online use only. Testing from the file path (i.e. file:// ) will not work as it will violate the security sandbox.

**Comment by Ceer00** [comment]
Hi,

Trying to install it from my local drive but having the error "manifest file missing, could not load". Does anyone have the same problem ? Or am I missing something ?
