### ISSUE TITLE
Data uri with flash fallback

### ISSUE THREAD

**Issue by miguelcobain** [dcneiner/Downloadify#25]
I'm writing this issue as an improvement suggestion.

It would be great to use data URI when possible. Something like what is in this gist: https://gist.github.com/2202660

When possible here means _when the size of the file is in the boundaries of the data URI limitations_ and _when data URI are supported in the browser_. This way we could avoid the use of flash in some cases. This would bring benefits such as efficiency and network bandwith savings (I think that flash files can't be cached).

What do you think?

**Comment by jlcooke** [comment]
I like it.  But some browsers (firefox) support data uri, but do not let you specify the filename.  It only "Partially" supports what downloadify does.

**Comment by togakangaroo** [comment]
This is no longer the case for firefox. Works fine using the download attribute: https://hacks.mozilla.org/2012/12/firefox-development-highlights-video-playbackrate-download-attribute/

**Comment by shaundon** [comment]
I've made a fork that does this - only just finished it, so may need a little more work. https://github.com/shaundon/Downloadomatic
