### ISSUE TITLE
Downloadify and Remote Binary Files

### ISSUE THREAD

**Issue by cbellini** [dcneiner/Downloadify#29]
If I have a binary file located at http://example.com/foo.exe and I wish to save it as bar.exe, how can I accomplish that with Downloadify?

**Comment by dcneiner** [comment]
If the file is already on the server, Downloadify probably won't help you out. I'd suggest you look into rewrite rules on your webserver. For instance, [on apache](http://stackoverflow.com/questions/1428331/is-it-possible-to-alias-a-filename-on-an-apache-webserver).
