### ISSUE TITLE
Allow Downloadify to run in offline mode

### ISSUE THREAD

**Issue by tmcchandra** [dcneiner/Downloadify#3]
I need the swf file to work in offline mode as my application is not served from webserver, but instead distributed as html file. Is there any way to allow file:// access to Downloadify?

**Comment by dcneiner** [comment]
I have not been able to find a way to make it work with a `file://` protocol yet. If I find something, I will surely update the library to support it.

**Comment by marrotte** [comment]
Doug:  Did you ever add support for offline (file://) mode?  If not, what's the issue?

**Comment by pignuts** [comment]
This can be done on a machine-by-machine basis, by specifying a 'trusted location' in your browser's Flash plugin settings.

Right-click on a Flash object and select 'Global settings...' from the contextual menu. Go to the 'Advanced' tab, and click 'Trusted location settings...' under Developer Tools. Add your local directory containing the Downloadify stuff. Restart your browser and it should now work.

**Comment by marrotte** [comment]
Doesn't seem to be work with Safari.  But, thanks for the advice.

**Comment by pignuts** [comment]
Working fine in Safari and Chrome on three machines I've tested. And that's certainly what that settings option is for. So maybe you've got something else going on? Does your Flash plugin have the right permissions?

**Comment by marrotte** [comment]
I'm getting

SecurityError:  Error #2060: Security sandbox violation: ExternalInterface caller file file:///Users/.../Downloadify/media/downloadify.swf cannot access file:///Users/.../Downloadify/test.html

Also,I notice this in your readme:

h2. Downloadify: Client Side File Creation

__Important! The swf has been compiled for online use only. Testing from the file path (i.e. file:// ) will not work as it will violate the security sandbox.__

**Comment by turutosiya** [comment]
Is it possible to avoid this probrem, following these steps?
1. In the object tag for the SWF file in the containing HTML page, set the following parameter:
   <param name="allowScriptAccess" value="always" />
2. In the SWF file, add the following ActionScript:
   flash.system.Security.allowDomain(sourceDomain)

descriped in :

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html#call()
