### ISSUE TITLE
Download via keyboard instead of mouse click

### ISSUE THREAD

**Issue by pbostrom** [dcneiner/Downloadify#32]
This might not be possible as explained in issue #6, but I thought I would mention it. I want to use the keyboard to tab to the element I have downloadified, and then use the Enter key to trigger the download.

**Comment by dcneiner** [comment]
This actually might be possible, but handlers would have to be added to it in the Flash file. No idea when I might add this in though – I'll leave it open since it is a possibility.

**Comment by codefactor** [comment]
Is there any plans on adding this functionality? Keyboard accessibility is important for section 508 compliance (which my page needs to have)
