### ISSUE TITLE
button position

### ISSUE THREAD

**Issue by WaffleGnome** [dcneiner/Downloadify#33]
ok i have some css positioning working, but what i really need it to place downloadify into my nav div(which seems to break the button)
I know how to position the downloadify button around the screen but I want to add it to my nav tag

but when i tried to append or prepend it into my nav downloadify broke

**Comment by dcneiner** [comment]
@WaffleGnome Can you provide a link to the page or some more information about it? I am not sure what is currently going on based on what you have described so far – sorry :(

**Comment by WaffleGnome** [comment]
Ok basically I want to add the downloadify button to my Navigation. but nothing seems to work

```
 <nav>
        <button></button>
 </nav>
```
