### ISSUE TITLE
Downlodify is not working, no error message at all

### ISSUE THREAD

**Issue by sankarge** [dcneiner/Downloadify#34]
I have the latest shock wave (11.9.900.117) add-on installed to my Firefox (24).

When i download and run the sample test.html file nothing is happening.But when i run the same demo linked (http://pixelgraphics.us/downloadify/test.html) HTML from Git hub works as expected.

Also i have tried this with my project too, same kind of output, nothing happens but the button hides.There are no error messages shown or can be caught since i cant go through the swfobject.js file.

I am using javascript alone, not jquery etc.

Is there anything that i am missing some basic stuffs?

Posted in http://stackoverflow.com/questions/19573697/downlodify-is-not-working-no-error-message-at-all too.

Thanks in advance.

**Comment by dcneiner** [comment]
Hey @Sankare555 – You need to be serving the demo or your project from an HTTP protocol. You cannot use Downloadify at the `file://` protocol due to how it was compiled. On Mac and Linux you can just run `python -m SimpleHTTPServer` in the root of your project to start a server, but there are solutions out there for Windows as well. Let me know if that helps.

**Comment by sankarge** [comment]
Yep dcneiner ;) I have found that I need to compile the as -> swf before using it. Wasn't ?

Yes, mine in HTTP based project and I was using as file:// protocol .

And I have a basic question with respect to the process of file creation by Downloadify  with the help of Flash.

I just saves the file with that content with given extension or it does any specific process for generating files (like pdf, xsl).

Thanks for your comments.

**Comment by dcneiner** [comment]
It will just save the content you give it when it calls back to your code. Any other process either should have happened before and just returned the content, or must happen synchronously in that callback.

**Comment by hoanhtien** [comment]
I am having the same problem with: <code>chrome-extension://</code>. Clicking on the button does not do anything.  No error message reported. The button does not hide though.
