### ISSUE TITLE
Downloadify does not work when the image dimensions are broken

### ISSUE THREAD

**Issue by Darker** [dcneiner/Downloadify#38]
I was trying to create invisible downloadify button, in the same manner in which classical upload file fields are being styled - making it transparent and hovering it over styled HTML elements.

My HTML button was 64x64 pixels, so I created 64x64 transparent image in hope it will work. Instead, it chaotically blinked and click event was never launched.

Since no errors were thrown (again) it took me quite a long while to realise what's wrong, and after creating 64x256 the flickering was fixed (but the flash still does not work).

**Comment by dougfarre** [comment]
Same issue here.  Did you manage to get anywhere?

**Comment by Darker** [comment]
Yes. In the current browsers, saveAs is quite reliable pure javascript solution. https://github.com/eligrey/FileSaver.js/
I really recommend it.
