### ISSUE TITLE
New line issue in textarea - Chrome and Firefox

### ISSUE THREAD

**Issue by MRedford** [dcneiner/Downloadify#4]
Hi

I'm creating a keyword research tool and am using Downloadify as a export option allowing users to save the keyword list from a HTML textarea.

The keywords need to be on new lines within the textarea. However when exporting this with keywords on multiple lines using Downloadify to save it as a txt file... all keywords are merged onto one line. It works fine with IE... but Chrome & Firefox share the same problem.

Is there anything we can do to fix this?

Thanks, Matt

**Comment by dcneiner** [comment]
How are you retrieving the text from the text area? I will test it, but if you use `$("#textarea_id").val()` it should work, thats how our demo is on the website. Let me know how you get the value so I can trouble shoot it for you.

**Comment by MRedford** [comment]
I'm using the same code as in the demo, just changing the textbox ID to mine and changing the downloadImage. I'm using this reference within the javascript block:

data: function(){ 
return document.getElementById('dropContent').value;
},

I've tried entering keywords on new lines using your demo too, exporting it as a txt file and it is coming back with the same problem as I'm finding on my site.

**Comment by dcneiner** [comment]
Ah, ok... so its a Windows line ending vs. Mac/Unix/Linux line ending problem then. Internet Explorer must automatically use `\r\n` that Windows expects, but Safari/FF does not. Try this code (Ugly, I know):

```
return document.getElementById('dropContent').value.replace(/\n/g, "\r\n").replace(/\r\r/g, "\r");
```

The first replace adds the needed `\r`, and the second removes repeated `\r` created by the replace. This second replace is really for Internet Explorer, so we dont' break it. Let me know if it works for you.

**Comment by MRedford** [comment]
Thanks, tried this and it works perfectly!

If you're interested this is the keyword tool I've been working on - http://www.keywordeye.co.uk. If you have any thoughts / feedback that would be great :)
