### ISSUE TITLE
Uploadify does call data and fileName callbacks but no dialog appears - google chrome

### ISSUE THREAD

**Issue by Darker** [dcneiner/Downloadify#41]
For some reason, uploadify does not produce dialog in Google chrome. On the same page, the Firefox has no problem.

Worst of all, not only that no errors are produced, but no of the `onError`, `onCancel` or `onComplete` callbacks is called. It simply seems like calling the `dataCallback` was the last thing the flash did.

This is quite a problem, because there is no way to use fallback when no error is called.

**Comment by meglio** [comment]
I can confirm that it doesn't work in Google Chrome nor in Firefox.
Both filename and data functions are called, however none of onXXX callbacks are called.
Dialog just doesn't appear.

**Comment by Darker** [comment]
I recommend http://eligrey.com/demos/FileSaver.js/. It's quite cross-browser and pure javascript.
