### ISSUE TITLE
Uploadify?

### ISSUE THREAD

**Issue by elite123** [dcneiner/Downloadify#5]
Firstly, this is just what I was looking for and works perfectly for my needs - thanks!

However, I also need to do the reverse (upload a file via flash to populate a javascript variable or html element) - I have to keep it all client side without interaction with the server.

I was wondering if this might be in the pipeline, or if you have any pointers to put this together myself.

Thanks

**Comment by ghost** [comment]
Use File-API for this issue. (http://www.w3.org/TR/FileAPI/)
