### ISSUE TITLE
File dialog hangs on Safari 9 on El Capitan

### ISSUE THREAD

**Issue by anowak** [dcneiner/Downloadify#55]
Surprisingly, this not happen on Yosemite with Safari 9. When you try to download the file, the file dialog shows up. Clicking 'save' button makes the whole browser hang.

Even the simplest demo (http://pixelgraphics.us/downloadify/test.html) hangs the entire Safari process (needs to be closed with Activity Monitor).

I've checked with other Flash apps and it seems to be a general problem with Flash after upgrade to El Capitan. I will fill a bug with Apple, but I wanted to give some sort of heads up here.

**Comment by dunkelmpl** [comment]
I can confirm the issue, and it's blocker for me

**Comment by KyleYu** [comment]
I found a workaround about this issue.
Preference=>Security=>Plug-in Settings=>Adobe Flash Player=>Switch from "Allow" to "Run in Unsafe Mode"
It will work.
Maybe certain process is considered as an unsafe behaviours by Safari.
Hope this issue could be solved soon...

**Comment by anowak** [comment]
Update to El Capitan (OS X 10.11.1) fixes this problem. I will submit a PR to the documentation.

**Comment by dunkelmpl** [comment]
Unfortunately update to the 10.11.1 doesn't solve issue on my computer. The sample - http://pixelgraphics.us/downloadify/test.html - hangs on save, making browser unresponsive too. Killing the flash process recovers browser.

**Comment by dunkelmpl** [comment]
Finally update OS X and Flash player to versions 10.11.4 and 20.0.0.286 respectively fixed the issue for me. One weird issue left though: in the recommended "real world usage" app http://starter.pixelgraphics.us/ (as well as in my own app) Downloadify now works fine, however simple example http://pixelgraphics.us/downloadify/test.html works one time and after that Flash player hangs, and pages with flash content don't open until I kill the Flash player process.
Anyway, main issue seems to be resolved now.

UPD: there's still the same behavior and issue in all the apps, mentioned above - sample, real app example and in my app: it works one time, then Flash player plugin hangs and doesn't let work with page anymore (the page doesn't get focus)
