### ISSUE TITLE
save file name with .xml triggers cancel event

### ISSUE THREAD

**Issue by m-kashif** [dcneiner/Downloadify#58]
I have tried the example which you provided.
http://pixelgraphics.us/downloadify/test.html

is not working in google chrome version 47.0.2526.106 m

Steps to reproduce issue.
1. go to this url http://pixelgraphics.us/downloadify/test.html
2. Enter file name testfile.xml
3. enter some xml content 
4. click on save to disk button
5. Error occurs you have cancelled the saving
Strange thing is that this is working great with other browsers and chrome prev version as well. If you will find any solution with that let me know, because i have flex tools and i am facing this error too. 

Thanks,
M Kashif

**Comment by jozip** [comment]
I've encountered the same error, though from what I gather, it was triggered by the latest flash update.
