### ISSUE TITLE
Trigger "save to disk" button call with external javascript

### ISSUE THREAD

**Issue by az9214** [dcneiner/Downloadify#6]
Sorry, I know this is not an issue. But, I did not know how else to get in touch with you. I Just wanted to know if there is any way to trigger the "save to disk" button call with an external Javascript function?

**Comment by dcneiner** [comment]
Sadly no. Flash 10 has a Security restriction that makes it impossible to trigger the "Save to Disk" button from anything other than direct interaction with the Flash document.

It stinks, but there is no way around it. Sorry!

**Comment by az9214** [comment]
Ok, Thank you for the prompt reply. I have one more related question, is it possible  to build in a callback to the mouse click action function in the Actionscript file that can later be called through Javascript instead of clicking the flash button to initiate save?

**Comment by dcneiner** [comment]
That is a very interesting question. I thought the same thing at one point, but it would require that they still click in the Flash document once per save. I guess you could do some sort of blocking loop in JavaScript but my guess is you would crash the browser or Flash... or get a "A script has stopped responding..." message.

Sorry I dont' have better news!
