### ISSUE TITLE
Downloadify Flash not displayed on IE8 (8.0.6001.18702)

### ISSUE THREAD

**Issue by az9214** [dcneiner/Downloadify#7]
The flash file is not being displayed on IE8, it works fine on Mozilla and Chrome. This issue also occurs with the Downloadify demo at http://www.downloadify.info/downloadify/test.html. I tried setting the 'transparent' parameter to false, but no luck. I am using the latest build of Downloadify with SWFObject 2.2.

**Comment by OrangeDog** [comment]
#9 related?
