### ISSUE TITLE
Binary data in a string makes the download button to fail

### ISSUE THREAD

**Issue by jontaylor** [dcneiner/Downloadify#8]
I'm using downloadify to save image data which is a binary string, this causes the download button to fail to popup the save dialog, this is tested against the online demo.

I will attach some data that causes it to fail (just paste it into the Downloadify Example.

**Comment by jontaylor** [comment]
Ok I can't attach a file so i'll post a link to some offending data

http://failswarm.com/binary_string.txt

**Comment by ghost** [comment]
I have the same problem.

**Comment by sebilasse** [comment]
Yes, same problem here. Any solution?

**Comment by jlcooke** [comment]
change dataType to 'base64' and return atob( yourBinaryData) instead.
