### ISSUE TITLE
downloadify.js line 91 yields Unknown runtime error in IE8

### ISSUE THREAD

**Issue by awhitford** [dcneiner/Downloadify#9]
I am unable to get this to work in IE8 due to the following Javascript error being reported:

Message: Unknown runtime error
Line: 91
Char: 34
Code: 0
URI: http://localhost:8080/downloadify.js

I am puzzled as to why IE is complaining (Chrome works).  Is there something special about this line?

**Comment by OrangeDog** [comment]
Likewise
Unknown runtime error  downloadify.min.js, line 3 character 1059

**Comment by OrangeDog** [comment]
See http://blog.rakeshpai.me/2007/02/ies-unknown-runtime-error-when-using.html

Basically if you give it a dom element that IE doesn't like adding nothing to (like &lt;table>) then it breaks.
